### PR TITLE
Grandslammer

### PR DESCRIPTION
**Pull request by grandslammer**

### CODE REVIEW

**Comment by grandslammer** [comment]
Created pull request. See the commit notes for more info!

**Comment by shreydan** [comment]
Please change ` #menu:hover` to `.menu:hover` in CSS for it to work! Thanks for the changes.

**Comment by grandslammer** [comment]
Change made.

**Comment by shreydan** [comment]
@grandslammer Thanks for the changes! Also, how did you get to know about this repository?

**Pull request merged**
